### ISSUE TITLE
Utilize Phobos skipOver

### ISSUE THREAD

**Issue by JesseKPhillips** [jmdavis/dxml#10]
https://github.com/jmdavis/dxml/blob/8dbc4a4a69dd98d30e896cfca9e12f600867c983/source/dxml/parser.d#L1859

You should be able to utilize: https://dlang.org/library/std/algorithm/searching/skip_over.skip_over.html
rather than the custom function.

**Comment by jmdavis** [comment]
It actually can't use it directly, because `stripStartsWith` doesn't take a range directly, and it handles incrementing the position, which `skipOver` doesn't do. However, `stripStartsWith` can be simplified to use `skipOver` internally.
