### ISSUE TITLE
decodeXML does not compile when given a range of type char[]

### ISSUE THREAD

**Issue by BitterlyIronic** [jmdavis/dxml#23]
```d
import std.stdio: writeln;
import dxml.util;

char[] str;

str ~= "hello";

str.decodeXML.writeln;
```

The above code fails to compile with `Error: cannot implicitly convert expression range of type char[] to string`. Tested with DMD 2.090.1 on Windows.

`wchar[]`, `dchar[]`, `string`, `wstring`, and `dstring` all work as expected.

**Comment by jmdavis** [comment]
It looks like adding `char[]` to the list of types tested triggers several bugs - in this particular case due to code that's specific to arrays of char only having been tested with `string`. So, I'll need to work my way through them.

**Comment by jmdavis** [comment]
Sorry for the delay. 0.4.2 should fix the problem.
